# Generated by Django 4.2.5 on 2023-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_box', models.FloatField()),
                ('weight_box', models.FloatField()),
            ],
            options={
                'db_table': 'Aggressor',
            },
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('image', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Frames',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('confidence_rate', models.FloatField()),
                ('fps', models.FloatField()),
            ],
            options={
                'db_table': 'Prediction',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timeframe', models.FloatField()),
            ],
            options={
                'db_table': 'Video',
            },
        ),
    ]
